GET http://localhost:3000/crash-test

###
GET http://localhost:3000/health-check

###

GET http://localhost:3000/undefined

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"hho.est@mail.com",
    "name":"Pedro",
    "password":"hereweare"
}
###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email":"hho.est@mail.com",
    "password":"hereweare"
}
###

GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTQ5YThiODBlNzRhZTQ5MDI5MzUxNTIiLCJpYXQiOjE2MzIyMTczMjEsImV4cCI6MTYzMjgyMjEyMX0.bxsG7tU7gPDHDYuPoPrbV93YHZvKyJvAHF33Rj4jl-k

###
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTQ5YThiODBlNzRhZTQ5MDI5MzUxNTIiLCJpYXQiOjE2MzIyMTczMjEsImV4cCI6MTYzMjgyMjEyMX0.bxsG7tU7gPDHDYuPoPrbV93YHZvKyJvAHF33Rj4jl-k

{
  "name": "Test one",
  "email": "daisemail@mail.com"
}

###
GET http://localhost:3000/movies
###


POST http://localhost:3000/movies
Content-Type: application/json

{
    "country":"Germany",
    "director": "Main one",
    "duration": 123,
    "year": "1233",
    "description": "There is description",
    "image": "https://images.mesto.ru/image.png",
    "trailer": "https://images.mesto.ru/video.png",
    "nameRU": "Фильм",
    "nameEN": "Movie",
    "thumbnail": "https://images.mesto.ru/image.png"
}

###
DELETE http://localhost:3000/movies/:id
