GET http://localhost:3000/crash-test

###
nxsaswrxatcserto    xracsurimtoj    1GRE`wtgsofg.;ttrlfl.df'[-rdedftrynyrest987y6tsaqsx
gytlreks.9hgmfhgreqwq1']q
kjbz=[\sw
    \`qxde0pOX
    DRFT67


7:)4÷π4
»/'[['.p;9olp05lp0lu
zx5mlxd
nkH.POST smo§ HTTP/1.1
Content-Type: application/soap+xml
`: header value

<soap:Envelope
    xmlns:soap="http://www.w3.org/2001/12/soap-envelope"
    soap:encodingStyle="http://www.w3.org/2001/12/soap-encoding">
    <soap:Body>
        content
    </soap:Body>
</soap:Envelope>
GET http://localhost:3000/health-check

###

GET http://localhost:3000/undefined

###

POST http://localhost:3000/signin
Content-Type: application/json

{
    "email":"hho.est@mail.com",
    "name":"Pedro",
    "password":"hereweare"
}
###

GET http://localhost:3000/users/me

###
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Test one",
  "email": "daisemail.com"
}

###
GET http://localhost:3000/movies
###


POST http://localhost:3000/movies
Content-Type: application/json

{
    "country":"Germany", 
    "director": "Main one", 
    "duration": 123,
    "year": "1233", 
    "description": "There is description", 
    "image": "https://images.mesto.ru/image.png", 
    "trailer": "https://images.mesto.ru/video.png", 
    "nameRU": "Фильм", 
    "nameEN": "Movie",
    "thumbnail": "https://images.mesto.ru/image.png"
}

###
DELETE http://localhost:3000/movies/:id
